### ISSUE TITLE
some questions about datasets

### ISSUE THREAD

**Issue by XiaoHao-Chen** [xuanqing94/AdvGAN#2]
First of all, thank you very much for your excellent work. I am a graduate student studying in mainland China. For some reasons, I can't download the Imagenet datasets. Then I want to test the code you provide with my own datasets. So can you give me some details about the data you use, such as the Imagenet-143 datasets you use, how many images are included in the data set, and how many images are used for training and testing?
Thank you very much for your help.

**Comment by xuanqing94** [comment]
@331801070049 There is a short description about the dataset: https://github.com/xuanqing94/RobGAN#step-0-data-preparation

The ImageNet-143 dataset is extracted by this script: https://github.com/pfnet-research/sngan_projection/blob/master/datasets/imagenet_dog_and_cat.py
