### ISSUE TITLE
What is perturbation used during training for CIFAR-10

### ISSUE THREAD

**Issue by aknirala** [xuanqing94/AdvGAN#7]
What is the perturbation used for training? Are all the columns in the results, which displays testing at different perturbation, are for a single model? i.e, for all columns the model has same adversarial perturbation (what is it?)? 

Results for CIFAR-10 as in Table1 of paper (at: https://web.cs.ucla.edu/~chohsieh/papers/RobustGAN_CVPR_new.pdf) is:
<table>
<tr><th>perturbation</th>    <td>0 (nat acc)</td>   <td>0.02</td>    <td>0.04</td>           <td>0.08</td></tr>
<tr><th>Rob-GAN (w/FT)</th> <td>81.1%</td>      <td>70.41%</td>  <td>57.43%</td>    <td>30.25%</td></tr>
</table>

A bit more detail, about my Q:
- Paper mentions: δ max ∈ np.arange(0, 0.1, 0.01). What does this mean? Does it mean maximum perturbation is 0.1 and step size is 0.01? 
- Code seems to limit perturbation to ε. [[line 24](https://github.com/xuanqing94/RobGAN/blob/8a478cf3435387753baee2d3a82d039236cc4fab/miscs/pgd.py#L10):] <pre>diff.clamp_(-epsilon, epsilon)</pre> The github page says to set ε to 0.03125, but this would effectively make it half as for this code input is in range [-1, 1] not [0, 1].

**Comment by HuangZuShu** [comment]
@aknirala Did you reproduce the result in paper?

**Comment by HuangZuShu** [comment]
> I am a little confused about `this would effectively make it half` .

I think that the perturbation is not releated to what you input. Because the perturbation produced is only limited by ε and has nothing to do with your input range, so I think the input range can be arbitrary. so i think [-1, 1] or [0, 1] is OK.
Is this view correct ?

**Comment by xuanqing94** [comment]
@aknirala I remembered I have answered your questions through the email. Please check it out to see if that works out.

Basically, for your q1, yes and I think this is to generate Fig 6 (left).
for your q2, yes if you compare perturbations with other papers that focus purely on adversarial robustness, our epsilon is not directly comparable (our 8/255 is effectively lower than theirs). But note that our paper isn't trying to set a new SOTA in adv defense.

**Comment by aknirala** [comment]
Hi @xuanqing94 
Yes you already answered my question. I should have updated it here and closed the issue.

Best.

**Comment by HuangZuShu** [comment]
> Hi @xuanqing94 Yes you already answered my question. I should have updated it here and closed the issue.
> 
> Best.

@xuanqing94 

Would you mind telling me why `The github page says to set ε to 0.03125, but this would effectively make it half as for this code input is in range [-1, 1] not [0, 1]` ?

Because I used to think the perturbation is not related to the range of input.

Or would you mind introducing some resouces for me to learn about it ?

Very very thank you !
